import tailwindcssAnimate from "tailwindcss-animate";
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      sans: ["Pretendard Variable", "sans-serif"],
    },
    extend: {
      colors: {
        adaptiveBackground: "var(--adaptiveBackground)",
        adaptiveGray: {
          "50": "var(--adaptiveGray50)",
          "100": "var(--adaptiveGray100)",
          "200": "var(--adaptiveGray200)",
          "300": "var(--adaptiveGray300)",
          "400": "var(--adaptiveGray400)",
          "500": "var(--adaptiveGray500)",
          "600": "var(--adaptiveGray600)",
          "700": "var(--adaptiveGray700)",
          "800": "var(--adaptiveGray800)",
          "900": "var(--adaptiveGray900)",
        },
        adaptiveOpacity: {
          "50": "var(--adaptiveOpacity50)",
          "100": "var(--adaptiveOpacity100)",
          "200": "var(--adaptiveOpacity200)",
          "300": "var(--adaptiveOpacity300)",
          "400": "var(--adaptiveOpacity400)",
          "500": "var(--adaptiveOpacity500)",
          "600": "var(--adaptiveOpacity600)",
          "700": "var(--adaptiveOpacity700)",
          "800": "var(--adaptiveOpacity800)",
          "900": "var(--adaptiveOpacity900)",
        },
        adaptiveRed: {
          "50": "var(--adaptiveRed50)",
          "100": "var(--adaptiveRed100)",
          "200": "var(--adaptiveRed200)",
          "300": "var(--adaptiveRed300)",
          "400": "var(--adaptiveRed400)",
          "500": "var(--adaptiveRed500)",
          "600": "var(--adaptiveRed600)",
          "700": "var(--adaptiveRed700)",
          "800": "var(--adaptiveRed800)",
          "900": "var(--adaptiveRed900)",
        },
        adaptiveBlue: {
          "50": "var(--adaptiveBlue50)",
          "100": "var(--adaptiveBlue100)",
          "200": "var(--adaptiveBlue200)",
          "300": "var(--adaptiveBlue300)",
          "400": "var(--adaptiveBlue400)",
          "500": "var(--adaptiveBlue500)",
          "600": "var(--adaptiveBlue600)",
          "700": "var(--adaptiveBlue700)",
          "800": "var(--adaptiveBlue800)",
          "900": "var(--adaptiveBlue900)",
        },
        adaptiveGreen: {
          "50": "var(--adaptiveGreen50)",
          "100": "var(--adaptiveGreen100)",
          "200": "var(--adaptiveGreen200)",
          "300": "var(--adaptiveGreen300)",
          "400": "var(--adaptiveGreen400)",
          "500": "var(--adaptiveGreen500)",
          "600": "var(--adaptiveGreen600)",
          "700": "var(--adaptiveGreen700)",
          "800": "var(--adaptiveGreen800)",
          "900": "var(--adaptiveGreen900)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      backgroundImage: {
        half: "linear-gradient(90deg, var(--adaptiveGray50) 0%, var(--adaptiveGray50) 50%, var(--adaptiveBackground) 50%, var(--adaptiveBackground) 100%);",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
export default config;
